CREATE TABLE  IF NOT EXISTS raw_observations (
  date VARCHAR(100) NOT NULL,
  time VARCHAR(100) NOT NULL,
  station_id double precision NOT NULL,
  col3 double precision DEFAULT NULL,
  col4 double precision DEFAULT NULL,
  col5 double precision DEFAULT NULL,
  col6 double precision DEFAULT NULL,
  col7 double precision DEFAULT NULL,
  col8 double precision DEFAULT NULL,
  col9 double precision DEFAULT NULL,
  col10 double precision DEFAULT NULL,
  col11 double precision DEFAULT NULL,
  col12 double precision DEFAULT NULL,
  col13 double precision DEFAULT NULL,
  col14 double precision DEFAULT NULL,
  col15 double precision DEFAULT NULL,
  col16 double precision DEFAULT NULL,
  col17 double precision DEFAULT NULL,
  col18 double precision DEFAULT NULL,
  col19 double precision DEFAULT NULL,
  col20 double precision DEFAULT NULL,
  col21 double precision DEFAULT NULL,
  col22 double precision DEFAULT NULL,
  col23 double precision DEFAULT NULL,
  col24 double precision DEFAULT NULL,
  col25 double precision DEFAULT NULL,
  col26 double precision DEFAULT NULL
);